name: CI Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [&quot;3.11&quot;, &quot;3.12&quot;]

    steps:
      - name: Baixar código
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Mostrar versão do Python
        run: python --version

      - name: Rodar testes
        run: python -m unittest discover -s tests -v